### ISSUE TITLE
Point Bitlocker Windows Pro et 10

### ISSUE THREAD

**Issue by dpettens** [louvainlinux/guide-installation#2]
Parler qu'il faut s'assurer que Bitlocker est désactivé avant de modifier le BIOS

**Comment by dpettens** [comment]
voir point 1 : [http://windowsreport.com/disable-bitlocker-windows-8/](http://windowsreport.com/disable-bitlocker-windows-8/)

**Comment by MaVdbussche** [comment]
A visiblement été corrigé au fil du temps
